message more meaningful when fails

diff --git a/wait b/wait
--- a/wait
+++ b/wait
@@ -41,7 +41,7 @@ do
   if [ "$seconds" -lt "$timeout" ]; then
     echo "  up!"
   else
-    echo "  ERROR: unable to connect" >&2
+    echo "  ERROR: unable to connect $host $port in last $timeout seconds" >&2
     exit 1
   fi
 done
